#!/bin/bash
# Merges upstream/stable into upstream/master
# Execute from any git repository or pass the directory as first argument

set -ueo pipefail -o xtrace
trap "echo 'Fix the merge conflicts and submit the pull request with prsend.'" ERR

DIR=${1:-$(pwd)}
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd "$DIR"

ORIGIN="${ORIGIN:-origin}"
UPSTREAM="${UPSTREAM:-upstream}"
MASTER="${MASTER:-master}"
STABLE="${STABLE:-stable}"

git fetch --multiple "$ORIGIN" "$UPSTREAM"
git checkout "$MASTER"
git merge --ff-only "$UPSTREAM/$MASTER"

# just in case `merge_stable` already exists
git branch -D "merge_$STABLE" || true

git checkout -b "merge_$STABLE"
git merge "$UPSTREAM/$STABLE"
# <- Solve merge conflicts (if any occurred)
"${SCRIPT_DIR}/pr_send"
git checkout "$MASTER"
popd
