#!/bin/bash
# Checkout a PR to an upstream repo from the CLI
# This will overwrite previous checkouts
# use: pr_checkout 5040
set -ueo pipefail

if [ -z "${1+x}" ] ; then
    echo "Usage: ./pr_checkout <123>"
    exit
fi

DIR="$(pwd)"
PR="$1"
UPSTREAM="${UPSTREAM:-upstream}"
MASTER="${MASTER:-master}"

cd "$DIR"

# delete existing branch
git checkout -q "$MASTER"
git fetch --prune "$UPSTREAM"
git branch -D "pr/$PR" 2>/dev/null || true
git fetch "$UPSTREAM" "refs/pull/$PR/head:pr/$PR"
git checkout "pr/$PR"
