#!/bin/bash
# Checkout a PR to an upstream repo from the CLI
# This will overwrite previous checkouts
# use: pr_checkout 5040
set -ueo pipefail

if [ -z "${1+x}" ] ; then
    echo "Usage: ./pr_checkout <123>"
    exit
fi

DIR=$(test -d ${DIR:-.} && cd ${DIR:-.} || true && pwd)
PR="$1"
UPSTREAM="${UPSTREAM:-upstream}"
MASTER="${MASTER:-master}"

cd "$DIR"

# delete existing branch
git checkout -q "$MASTER"
git fetch --prune "$UPSTREAM" "$MASTER" "+refs/pull/$PR/head:pr/$PR"
git merge --ff-only "$UPSTREAM/$MASTER"
git checkout "pr/$PR"
